### ISSUE TITLE
Error de Hydrating

### ISSUE THREAD

**Issue by Kellokes** [lucaspinheirogit/react-i18n-tutorial#24]
Lucas, 

Primeiramente gostaria de agradecer pelo código, tem me ajudado muito.

Estou tentando um erro peculiar com o código, erro de hidratação do react:

```
Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Component Stack
span
Translator
div
a
```

E ele tem ocasionando justamente no componente de Tradução, vc sabe o que pode ser?

**Comment by Kellokes** [comment]
Detalhe estou usando typescript, tive que alterar o código para funcionar.

**Comment by lucaspinheirogit** [comment]
oi @Kellokes , tu consegue me mandar mais detalhes do erro e do codigo pra mim dar uma olhada?

**Comment by Kellokes** [comment]
Resolvi aqui fazendo a seguinte adptação no código do Translator.tsx:

```
import { useTranslation } from 'react-i18next';


interface TranslatorProps {
  path: string;
}

const Translator: React.FC<TranslatorProps> = ({ path }) => {
  const { t } = useTranslation();

  return <span dangerouslySetInnerHTML={{ __html: t(path) }} />;
};

export default Translator;
```

Mas depois o React reclama do uso do dangerouslySetInnerHTML, mas não gerar um problema para mim em produção.
